# Starship Configuration Example
#Windows CMD starship file

"$schema" = 'https://starship.rs/config-schema.json'


format = """
[â”Œâ”€](white)\
[î‚¶](#F8F6E3)\
[$os]()\
[$username](bg:#F8F6E3 fg:#7AA2E3)\
[î‚°](bg:#86BBD8 fg:#F8F6E3)\
[ ï‚› ](bg:#86BBD8 fg:white)\
$git_branch\
$git_status\
[î‚°](fg:#86BBD8 bg:#6AD4DD)\
[ in ](bg:#6AD4DD fg:white)\
[î‚°](bg:#ADF7B6 fg:#6AD4DD)\ 
 [ î—¾$directory](fg:black bg:#ADF7B6)\
 [î‚°](fg:#ADF7B6)\ 
\n\
[â””â”€](white)\
[î‚¶](#ADF7B6)\
[$time îª… cmd :>](fg:black bg:#ADF7B6)\
[î‚°](fg:#ADF7B6)\
[ ]()\
 """

# Ustawienia nazwy uÅ¼ytkownika
[username]
style_user = "yellow"
format = " $user "
show_always = true
disabled = false

# Ustawienia nazwy hosta
[hostname]
#ssh_only = false
#format = " on <[$hostname]($style)>"
#style = "bold white"
#disabled = false

[os]
disabled = false
style = "bg:#F8F6E3 fg:#7AA2E3"

[os.symbols]
Windows = "ó°²"
Ubuntu = "ó°•ˆ"
SUSE = "ïŒ”"
Raspbian = "ó°¿"
Mint = "ó°£­"
Macos = "ó°€µ"
Manjaro = "ïŒ’"
Linux = "ó°Œ½"
Gentoo = "ó°£¨"
Fedora = "ó°£›"
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœ"
Arch = "ó°£‡"
Artix = "ó°£‡"
CentOS = "ïŒ„"
Debian = "ó°£š"
Redhat = "ó±„›"
RedHatEnterprise = "ó±„›"

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[ïº $time ](fg:color_fg0 bg:color_bg1)]($style)'

# Ustawienia katalogu
[directory]
disabled = false
truncation_length = 0
#style = "#BD93F9"  # Kolor fioletowy
style = "fg:black bg:#ADF7B6"
#home_symbol = 'ó°‹œ ~'

read_only = "ğŸ”’"
read_only_style = "red"
format = "[ $path ]($style)[$read_only]($read_only_style)"

# Konfiguracja moduÅ‚u 'character'
#[character]
#format = '[â¯](bold yellow)'
#format = "$symbol "
#symbol = '[âœ](#FFFFA5)'


# WyÅ‚Ä…czenie moduÅ‚u 'package', ukrycie go caÅ‚kowicie z prompta
[package]
disabled = true

#[directory.substitutions]
#"Documents" = "ó°ˆ™ "
#"Downloads" = "ï€™ "
#"Music" = "ó°š "
#"Pictures" = "ï€¾ "
#"Developer" = "ó°²‹ "


#git 
[git_branch]
symbol = "ï˜"
style = "bg:#86BBD8 fg:white"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#86BBD8 fg:white"
format = '[$all_status$ahead_behind ]($style)'
